name: Justin Gullickson Riversurfer
favicon: null
layout_spectrum: 0.8032420550007373
typography_spectrum: 0.4117094553075731
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.12488660681992769
  lightness: 0.6623444503638893
  saturation: 0.9931183271110058
  rhythmicContrast: 0.1049119713716209
purpose: []
