name: Justin Gullickson Riversurfer
favicon: null
layout_spectrum: 0.8032420550007373
typography_spectrum: 0.30747
title: Riversurfing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfeff'
    - '#33351c'
    - '#010101'
    - '#b1b7b9'
    - '#868069'
  brandStrength: 0.12488660681992769
  lightness: 0.6623444503638893
  saturation: 0.9931183271110058
  rhythmicContrast: 0.1049119713716209
purpose: []
